easy_admin:
    list:
      # hide actions by default in a dropdown menu...
#      collapse_actions: true
      actions: ['show', 'edit', 'delete']
    design:
        #form_theme: ['@FOSCKEditor/Form/ckeditor_widget.html.twig']
        form_theme:
          - '@EasyAdmin/form/bootstrap_4.html.twig'
          - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

    entities:
#        Client:
#             class: App\Entity\Client
#             form:
#                   fields:
#                         - { property: 'name' }
#                         - { property: 'email' }
#                         - { property: 'telephone' }
#                         - { property: 'country'}
#                         - { property: 'locale', type: 'choice', type_options: '%easyadmin.options.language.choices%' }
#                         - { property: 'bookings' }

        Booking:
              class: App\Entity\Booking


        Food:
              class: App\Entity\Food


        User:
              class: App\Entity\User


#        GalleryImage:
#              class: App\Entity\GalleryImage
#              form:
#                  fields:
###                      - { property: 'title'}
#                      - { property: 'imageFile', type: 'vich_image' }
###                      - { property: 'alternativeText'}
###                      - { property: 'taxiService'}
##              list:
##                  fields:
##                      - { property: 'title'}
##                      - { property: 'image', type: 'image', base_path: '%app.path.uploaded_images%' }
##                      - { property: 'taxiService'}
##
#
